### ISSUE TITLE
Wrong redraw under Raspberry OS after zoom out

### ISSUE THREAD

**Issue by kosmosgit** [Milo-D/libvmcu-Virtual-MCU-Library#41]
If you want to zoom out under Raspberry OS in the terminal window with CTRL + Shift + -, the terminal window is reduced, but only the frames are rebuilt instead of the characters and if you then want to perform a step with n and Enter to bring about an update, MDX with after a memory error message.
![MDX](https://user-images.githubusercontent.com/60920023/101410192-474ca580-38df-11eb-9edf-074aba499a11.png)
![MDX_n](https://user-images.githubusercontent.com/60920023/101410194-487dd280-38df-11eb-9545-f063bbfedb20.png)
![MDX_zoom_out](https://user-images.githubusercontent.com/60920023/101410196-487dd280-38df-11eb-9c64-a3e317d1ce28.png)

**Comment by Milo-D** [comment]
Thank you for submitting this bug. A fix is on its way.

**Comment by Milo-D** [comment]
I am currently moving the debugger to another repository, so I will close this issue.
