### ISSUE TITLE
prog.c does not exist

### ISSUE THREAD

**Issue by peterpt** [Milo-D/libvmcu-Virtual-MCU-Library#71]
on your readme you wrote this compile intruction , but the reality is that prog.c does not exist in that directory .

gcc -Iengine/include/libvmcu/ -c prog.c -o prog.o

**Comment by Milo-D** [comment]
Hey @peterpt,

sorry for the confusion. The sentence

> Let's say, we have a file called prog.c on top level of this repository

describes a hypothetical case, in which we already have created the example program ```prog.c``` on top level. You can copy this snippet

```c
/* prog.c */

#include "libvmcu_analyzer.h"
#include "libvmcu_system.h"

int main(void) {
    
    /* do something */
    return 0;
}
```

and use it as starting point. Feel free to browse the (incomplete) wiki (https://github.com/Milo-D/libvmcu-Virtual-MCU-Library/wiki) and```driver/``` directory to learn how to use the library.

But note, that this project is still unfinished and there is a lot to improve/change. But I currently lack the energy to work on it. I might resume the development in the future though.

With that being said, feel free to experiment with the project and maybe even modify it to suit your needs.

If this resolves your issue, please close this issue :)

**Comment by peterpt** [comment]
Thank you for the tip .
Nice work on this tool , thank you .
I would like to help but C language is not my area .
